### ISSUE TITLE
MultiGPU problem

### ISSUE THREAD

**Issue by robinzixuan** [FMInference/FlexGen#105]
is it possible for run 4 * 8 2080-Ti instead of 1 16G GPU

**Comment by Ying1123** [comment]
It is possible, but notice that the scalability of multi-GPU on a single machine is limited (bounded by the PCIe bandwidth). FlexGen has experimental support for multi-GPU with one GPU per machine and shows promising results with super-linear scalability. 
Actually, if you have that many 2080-Ti, there is no need to use offloading. It is better to leverage model parallelism to do the inference all on GPUs.

**Comment by robinzixuan** [comment]
When I try to use multigpu, I set the num-gpu-batches to 4. However, there is only one GPU running when I type Nvidia-smi

**Comment by Ying1123** [comment]
What is your exact command?

**Comment by robinzixuan** [comment]
I solved
