### ISSUE TITLE
PermissionError on delete

### ISSUE THREAD

**Issue by xaedes** [FMInference/FlexGen#29]
When using offloading in flex_opt I get a PermissionError on windows.

This line throws the error:

https://github.com/FMInference/FlexGen/blob/main/flexgen/pytorch_backend.py#L664
```
os.remove(tensor.data)
```

It happens, because the filepath `tensor.data` is still open as memmap. 
When we executing again the existing file would just be overwritten, 
so it would be fine, when the `os.remove` call fails. 
-> I fixed it locally by wrapping it in try catch and pass on PermissionError.

**Comment by Ying1123** [comment]
Thanks for reporting this. We have encountered similar errors before, but very rarely.
I guess there are still some deep bugs in our async copy engine. I will take a deeper look later.
