### ISSUE TITLE
Why is offloading necessary at all?

### ISSUE THREAD

**Issue by amogkam** [FMInference/FlexGen#3]
If I have enough GPUs would just using pipeline parallelism with no offloading be the most optimal for high throughput/low latency?

**Comment by Ying1123** [comment]
If you have enough GPUs, no need to do offloading, yes. FlexGen also supports that. One interesting observation in sec 6.3 of the paper is that you can achieve a lower cost for a single GPU at home than multiple GPUs in the cloud.

**Comment by neuhaus** [comment]
Will having an nvlink bridge between two RTX 3090 make for a significant improvement when offloading?

**Comment by Ying1123** [comment]
I guess not. Offloading is bound by PCIE bandwidth and disk bandwidth. Adding NVLink between two GPUs does not help too much.
