### ISSUE TITLE
Offloading on Windows?

### ISSUE THREAD

**Issue by akhilshastrinet** [FMInference/FlexGen#6]
I've got 24GB ram and a 3070, trying to run the OPT-30b and offload everything to SSD, it seems to run out of memory without writing anything to disk ?

Have tried a few things like the below however I don't see any disk space being used up before it throws an out of memory exception?

python -m flexgen.flex_opt --model facebook/opt-30b --percent 0 0 100 0 100 0  --offload-dir f:/modelcache
python -m flexgen.flex_opt --model facebook/opt-30b --percent 0 0 0 0 0 0 --offload-dir f:/modelcache

**Comment by Ying1123** [comment]
Do you have a screenshot or do you know which line the out-of-memory happen at?

**Comment by akhilshastrinet** [comment]
Thanks for following up, I switched to using WSL (Ubuntu) on Windows and managed to get the 6.7B version to load , however it keeps getting a segmentation fault when trying to generate text. I'll close the issue for now, will try again when I can beef up my computer a bit. Thanks!
