### ISSUE TITLE
Offloading to disk does not work (opt-66b)

### ISSUE THREAD

**Issue by Paethon** [FMInference/FlexGen#61]
I just tried running `flexgen.flex_opt` with the following command:
`python3 -m flexgen.flex_opt --model facebook/opt-66b --percent 0 0 100 0 100 0 --offload-dir ~/tmp/offload/` but this only fills the CPU memory until the process is killed by the OS and the folder `~/tmp/offload/` stays completely empty

System:
- Arch Linux
- 128GiB RAM
- RTX3090

**Comment by Ying1123** [comment]
Do you know which line the OOM happens at?
One possible reason is that it happens during the weight download and weight conversion. In this case, you can rent a machine with more CPU ram and copy the converted weights.

**Comment by Ying1123** [comment]
This should be fixed by #69. It is merged into the main branch. Could you try it now?
Also, this is a duplication of #11

**Comment by Paethon** [comment]
Sorry, was not available for a few days. Going to have a look, thanks! :+1:
