### ISSUE TITLE
Where is the chatbot? I miss it!

### ISSUE THREAD

**Issue by fuhengwu2021** [FMInference/FlexGen#87]
Why delete it?

**Comment by brandonj60** [comment]
Agreed. They also deleted all the readme instructions for some reason.

**Comment by Ph0rk0z** [comment]
Use https://github.com/oobabooga/text-generation-webui

**Comment by Nidelon** [comment]
It's not too good to remove all instructions from the README and example files, while not adding docs. This is extremely confusing for beginners and generally complicates the understanding of the library.

**Comment by SoftologyPro** [comment]
Add another request to bring the chatbot back.  If possible also get it to be able to handle multiple line responses.

**Comment by fuhengwu2021** [comment]
Also is it able to use 2 GPUs with FlexGen and how?

**Comment by cidrugHug8** [comment]
Perhaps they removed it for fear of abuse.

**Comment by Nidelon** [comment]
> Perhaps they removed it for fear of abuse.

It is unlikely, since there was just an input by the type of Person: Bot:, nothing special.
And to think about the abuse of this library is slightly stupid, just as it is possible for the same reasons, for example, to prohibit the use of Google Colab.
